public class data1 {
    public static void main(String[] args) {
        
    int a=10;
    int b=25;

    int sum=a+b;
    int sub=a-b;
    int div=a/b;
    int mul=a*b;
    System.out.println("the sum of a and b is "+sum);
    System.out.println("the sub of a and b is "+sub);
    System.out.println("the div of a and b is "+div);
    System.out.println("the mul of a and b is "+mul);
    }}
    